import Foundation
import InstantCore

enum ConnectionCopyKey: String, CaseIterable {
    case intro, missing, configure, ready, openSettings, preserved, checkFields
    case checkNetwork, later, checkAccount, shorten, rephrase
    case invalidURL, invalidKey, invalidModel, keychain, keychainSave
    case authentication, permission, model, endpoint, quota, rateLimited, unavailable
    case contextLimit, rejected, offline, network, timeout, certificate, empty, format
    case interrupted, filtered, outputLimit, unknown, continueAnswer
}

struct ConnectionCopy {
    let language: Language
    static var translatedLanguages: Set<String> { Set(rows.keys) }
    static func entryCount(for language: String) -> Int { rows[language]?.components(separatedBy: "|").count ?? 0 }
    subscript(_ key: ConnectionCopyKey) -> String {
        let values = (Self.rows[language.id] ?? Self.rows["en"]!).components(separatedBy: "|")
        let index = ConnectionCopyKey.allCases.firstIndex(of: key)!
        guard values.indices.contains(index) else { return Self.rows["en"]!.components(separatedBy: "|")[index] }
        return values[index]
    }

    private static let rows: [String: String] = [
        "ar": "يتيح لك Instant إجابات سريعة وترجمة بلغتين في أي وقت.|يرجى ملء {fields}.|{settings} (⌘,)، ثم اضغط Enter للمتابعة بعد الإعداد.|تم إدخال بيانات الاتصال. يمكنك الآن طرح سؤال.|فتح الإعدادات|تم الاحتفاظ بالنص الذي وصل سابقًا.|تحقق من {fields}.|تحقق من اتصال الشبكة وإعدادات الوكيل.|حاول مجددًا بعد قليل.|تحقق من حصة حسابك وحدود الاستخدام لدى المزوّد.|اختصر السؤال أو أرشف المحادثة ثم حاول مجددًا.|أعد صياغة السؤال وحاول مجددًا.|Base URL غير صالح. استخدم عنوان API عبر HTTPS مثل https://…/v1.|تنسيق API Key غير صالح. الصق المفتاح الكامل فقط.|استخدم معرّف نموذج المزوّد دون مسافات.|تعذرت قراءة API Key من سلسلة المفاتيح. اسمح بالوصول أو أدخله في الإعدادات.|تعذر حفظ API Key في سلسلة المفاتيح. اسمح بالوصول وحاول مجددًا.|فشلت المصادقة باستخدام API Key.|رُفض الوصول إلى النموذج أو الخدمة.|لم يُعثر على النموذج أو أنه غير متاح عبر هذا العنوان.|تعذر استخدام عنوان API.|نفدت حصة الخدمة أو فُرضت عليها قيود.|عدد الطلبات كبير جدًا.|خدمة النموذج غير متاحة مؤقتًا.|يتجاوز الإدخال أو المحادثة حد النموذج.|رفضت الخدمة الطلب أو لا تدعم هذا API.|لا يوجد اتصال بالإنترنت.|تعذر الاتصال بالخدمة.|انتهت مهلة الطلب.|فشل التحقق من شهادة HTTPS.|لم تُرجع الخدمة إجابة قابلة للعرض.|الاستجابة ليست بتنسيق بث مدعوم.|انقطعت الإجابة قبل اكتمالها.|لم تقبل الخدمة هذا الطلب.|بلغت الإجابة حد إخراج النموذج.|تعذر إكمال الطلب.|يمكنك أن تطلب من النموذج متابعة الإجابة.",
        "he": "Instant זמין תמיד לתשובות מהירות ולתרגום בשתי שפות.|יש למלא {fields}.|{settings} (⌘,), ולאחר ההגדרה ללחוץ על Enter להמשך.|פרטי החיבור הוזנו. כעת אפשר לשאול שאלה.|פתיחת הגדרות|הטקסט שהתקבל קודם נשמר.|יש לבדוק את {fields}.|יש לבדוק את חיבור הרשת ואת הגדרות הפרוקסי.|אפשר לנסות שוב בעוד רגע.|יש לבדוק את המכסה ומגבלות השימוש אצל הספק.|יש לקצר את השאלה או להעביר את השיחה לארכיון ולנסות שוב.|יש לנסח מחדש את השאלה ולנסות שוב.|Base URL אינו תקין. יש להשתמש בכתובת API מסוג HTTPS, למשל https://…/v1.|הפורמט של API Key אינו תקין. יש להדביק רק את המפתח המלא.|יש להשתמש במזהה המודל של הספק ללא רווחים.|לא ניתן לקרוא את API Key מצרור המפתחות. יש לאפשר גישה או להזין אותו בהגדרות.|לא ניתן לשמור את API Key בצרור המפתחות. יש לאפשר גישה ולנסות שוב.|האימות של API Key נכשל.|הגישה למודל או לשירות נדחתה.|המודל לא נמצא או אינו זמין בכתובת זו.|לא ניתן להשתמש בכתובת ה-API.|מכסת השירות נוצלה או הוגבלה.|יותר מדי בקשות.|שירות המודל אינו זמין זמנית.|הקלט או השיחה חורגים ממגבלת המודל.|השירות דחה את הבקשה או אינו תומך ב-API זה.|אין חיבור לאינטרנט.|לא ניתן להתחבר לשירות.|הבקשה חרגה מזמן ההמתנה.|אימות תעודת HTTPS נכשל.|השירות לא החזיר תשובה שניתן להציג.|התשובה אינה בפורמט זרימה נתמך.|התשובה נקטעה לפני השלמתה.|השירות לא קיבל בקשה זו.|התשובה הגיעה למגבלת הפלט של המודל.|לא ניתן להשלים את הבקשה.|אפשר לבקש מהמודל להמשיך את התשובה.",
        "fa": "با Instant همیشه به پاسخ‌های سریع و ترجمهٔ دوزبانه دسترسی دارید.|لطفاً {fields} را وارد کنید.|{settings} (⌘,) و پس از تکمیل تنظیمات، برای ادامه Enter را بزنید.|اطلاعات اتصال وارد شد. اکنون می‌توانید سؤال بپرسید.|باز کردن تنظیمات|متن دریافت‌شدهٔ قبلی حفظ شده است.|{fields} را بررسی کنید.|اتصال شبکه و تنظیمات پراکسی را بررسی کنید.|کمی بعد دوباره تلاش کنید.|سهمیه و محدودیت‌های مصرف حساب را نزد ارائه‌دهنده بررسی کنید.|سؤال را کوتاه کنید یا گفتگو را بایگانی کرده و دوباره تلاش کنید.|سؤال را بازنویسی کنید و دوباره تلاش کنید.|Base URL نامعتبر است. از آدرس API با HTTPS مانند https://…/v1 استفاده کنید.|قالب API Key نامعتبر است. فقط کلید کامل را جای‌گذاری کنید.|شناسهٔ مدل ارائه‌دهنده را بدون فاصله وارد کنید.|خواندن API Key از دسته‌کلید ممکن نشد. دسترسی را مجاز کنید یا کلید را در تنظیمات وارد کنید.|ذخیرهٔ API Key در دسته‌کلید ممکن نشد. دسترسی را مجاز کنید و دوباره تلاش کنید.|احراز هویت API Key ناموفق بود.|دسترسی به مدل یا سرویس رد شد.|مدل پیدا نشد یا در این آدرس در دسترس نیست.|استفاده از آدرس API ممکن نشد.|سهمیهٔ سرویس تمام شده یا محدود شده است.|تعداد درخواست‌ها بیش از حد است.|سرویس مدل موقتاً در دسترس نیست.|ورودی یا گفتگو از محدودیت مدل فراتر رفته است.|سرویس درخواست را رد کرده یا از این API پشتیبانی نمی‌کند.|اتصال اینترنت برقرار نیست.|اتصال به سرویس ممکن نشد.|مهلت درخواست تمام شد.|تأیید گواهی HTTPS ناموفق بود.|سرویس پاسخی قابل نمایش برنگرداند.|قالب جریان پاسخ پشتیبانی نمی‌شود.|پاسخ پیش از تکمیل قطع شد.|سرویس این درخواست را نپذیرفت.|پاسخ به حد خروجی مدل رسید.|تکمیل درخواست ممکن نشد.|می‌توانید از مدل بخواهید پاسخ را ادامه دهد.",
        "hi": "Instant से कभी भी तुरंत जवाब और दो भाषाओं में अनुवाद पाएँ।|कृपया {fields} भरें।|{settings} (⌘,) और सेटअप के बाद जारी रखने के लिए Enter दबाएँ।|कनेक्शन की जानकारी भर दी गई है। अब प्रश्न पूछ सकते हैं।|सेटिंग्स खोलें|पहले प्राप्त पाठ सुरक्षित है।|{fields} जाँचें।|नेटवर्क कनेक्शन और प्रॉक्सी जाँचें।|थोड़ी देर बाद फिर कोशिश करें।|प्रदाता के खाते का कोटा और उपयोग सीमा जाँचें।|प्रश्न छोटा करें या बातचीत संग्रह करके फिर कोशिश करें।|प्रश्न दूसरे शब्दों में लिखकर फिर कोशिश करें।|Base URL अमान्य है। https://…/v1 जैसे HTTPS API पते का उपयोग करें।|API Key का प्रारूप अमान्य है। केवल पूरी कुंजी पेस्ट करें।|प्रदाता का मॉडल ID बिना खाली स्थान के भरें।|कीचेन से API Key नहीं पढ़ी जा सकी। पहुँच की अनुमति दें या सेटिंग्स में फिर भरें।|API Key कीचेन में सेव नहीं हुई। पहुँच की अनुमति देकर फिर कोशिश करें।|API Key का प्रमाणीकरण विफल रहा।|मॉडल या सेवा की पहुँच अस्वीकृत हुई।|मॉडल नहीं मिला या इस पते पर उपलब्ध नहीं है।|API पते का उपयोग नहीं किया जा सका।|सेवा का कोटा समाप्त या सीमित है।|बहुत अधिक अनुरोध हैं।|मॉडल सेवा अस्थायी रूप से उपलब्ध नहीं है।|इनपुट या बातचीत मॉडल की सीमा से अधिक है।|सेवा ने अनुरोध अस्वीकार किया या यह API समर्थित नहीं है।|इंटरनेट कनेक्शन नहीं है।|सेवा से कनेक्ट नहीं हो सका।|अनुरोध का समय समाप्त हो गया।|HTTPS प्रमाणपत्र की जाँच विफल रही।|सेवा ने दिखाने योग्य उत्तर नहीं दिया।|उत्तर का स्ट्रीमिंग प्रारूप समर्थित नहीं है।|उत्तर पूरा होने से पहले रुक गया।|सेवा ने यह अनुरोध स्वीकार नहीं किया।|उत्तर मॉडल की आउटपुट सीमा तक पहुँच गया।|अनुरोध पूरा नहीं हो सका।|जवाब आगे बढ़ाने के लिए एक और प्रश्न पूछ सकते हैं।",
        "bn": "Instant দিয়ে যেকোনো সময় দ্রুত উত্তর ও দুই ভাষায় অনুবাদ পান।|অনুগ্রহ করে {fields} পূরণ করুন।|{settings} (⌘,) এবং সেটআপ শেষ হলে চালিয়ে যেতে Enter চাপুন।|সংযোগের তথ্য পূরণ করা হয়েছে। এখন প্রশ্ন করতে পারেন।|সেটিংস খুলুন|আগে পাওয়া লেখা সংরক্ষিত আছে।|{fields} পরীক্ষা করুন।|নেটওয়ার্ক সংযোগ ও প্রক্সি পরীক্ষা করুন।|কিছুক্ষণ পরে আবার চেষ্টা করুন।|সরবরাহকারীর অ্যাকাউন্টে কোটা ও ব্যবহারের সীমা পরীক্ষা করুন।|প্রশ্ন ছোট করুন বা কথোপকথন সংরক্ষণ করে আবার চেষ্টা করুন।|প্রশ্ন অন্যভাবে লিখে আবার চেষ্টা করুন।|Base URL অবৈধ। https://…/v1-এর মতো HTTPS API ঠিকানা ব্যবহার করুন।|API Key-এর বিন্যাস অবৈধ। শুধু সম্পূর্ণ কী পেস্ট করুন।|ফাঁকা স্থান ছাড়া সরবরাহকারীর মডেল ID দিন।|কীচেন থেকে API Key পড়া যায়নি। প্রবেশের অনুমতি দিন বা সেটিংসে আবার লিখুন।|কীচেনে API Key সংরক্ষণ করা যায়নি। অনুমতি দিয়ে আবার চেষ্টা করুন।|API Key যাচাই ব্যর্থ হয়েছে।|মডেল বা পরিষেবায় প্রবেশের অনুমতি মেলেনি।|মডেল পাওয়া যায়নি বা এই ঠিকানায় উপলব্ধ নয়।|API ঠিকানা ব্যবহার করা যায়নি।|পরিষেবার কোটা শেষ বা সীমাবদ্ধ।|অনেক বেশি অনুরোধ।|মডেল পরিষেবা সাময়িকভাবে অনুপলব্ধ।|ইনপুট বা কথোপকথন মডেলের সীমা ছাড়িয়েছে।|পরিষেবা অনুরোধ প্রত্যাখ্যান করেছে বা এই API সমর্থিত নয়।|ইন্টারনেট সংযোগ নেই।|পরিষেবায় সংযোগ করা যায়নি।|অনুরোধের সময়সীমা শেষ হয়েছে।|HTTPS সার্টিফিকেট যাচাই ব্যর্থ হয়েছে।|পরিষেবা দেখানোর মতো উত্তর ফেরত দেয়নি।|উত্তরের স্ট্রিমিং বিন্যাস সমর্থিত নয়।|উত্তর শেষ হওয়ার আগে থেমে গেছে।|পরিষেবা এই অনুরোধ গ্রহণ করেনি।|উত্তর মডেলের আউটপুট সীমায় পৌঁছেছে।|অনুরোধ সম্পূর্ণ করা যায়নি।|উত্তর চালিয়ে যেতে মডেলকে বলতে পারেন।",
        "ur": "Instant سے کسی بھی وقت فوری جواب اور دو زبانوں میں ترجمہ حاصل کریں۔|براہ کرم {fields} درج کریں۔|{settings} (⌘,) اور ترتیب مکمل ہونے پر Enter دبا کر جاری رکھیں۔|رابطے کی معلومات درج ہو گئی ہیں۔ اب سوال کر سکتے ہیں۔|ترتیبات کھولیں|پہلے موصول ہونے والا متن محفوظ ہے۔|{fields} کی جانچ کریں۔|نیٹ ورک کنکشن اور پراکسی کی جانچ کریں۔|تھوڑی دیر بعد دوبارہ کوشش کریں۔|فراہم کنندہ کے اکاؤنٹ کا کوٹا اور استعمال کی حدود دیکھیں۔|سوال مختصر کریں یا گفتگو محفوظ کر کے دوبارہ کوشش کریں۔|سوال دوسرے الفاظ میں لکھ کر دوبارہ کوشش کریں۔|Base URL درست نہیں۔ https://…/v1 جیسے HTTPS API پتے کا استعمال کریں۔|API Key کی ساخت درست نہیں۔ صرف مکمل کلید پیسٹ کریں۔|فراہم کنندہ کا ماڈل ID خالی جگہوں کے بغیر درج کریں۔|کی چین سے API Key نہیں پڑھی جا سکی۔ رسائی کی اجازت دیں یا ترتیبات میں دوبارہ درج کریں۔|API Key کی چین میں محفوظ نہیں ہو سکی۔ رسائی کی اجازت دے کر دوبارہ کوشش کریں۔|API Key کی تصدیق ناکام رہی۔|ماڈل یا سروس تک رسائی مسترد کر دی گئی۔|ماڈل نہیں ملا یا اس پتے پر دستیاب نہیں۔|API پتہ استعمال نہیں کیا جا سکا۔|سروس کا کوٹا ختم یا محدود ہے۔|بہت زیادہ درخواستیں ہیں۔|ماڈل سروس عارضی طور پر دستیاب نہیں۔|ان پٹ یا گفتگو ماڈل کی حد سے زیادہ ہے۔|سروس نے درخواست مسترد کی یا یہ API معاونت یافتہ نہیں۔|انٹرنیٹ کنکشن نہیں ہے۔|سروس سے رابطہ نہیں ہو سکا۔|درخواست کا وقت ختم ہو گیا۔|HTTPS سرٹیفکیٹ کی تصدیق ناکام رہی۔|سروس نے دکھانے کے قابل جواب نہیں دیا۔|جواب کی اسٹریمنگ ساخت معاونت یافتہ نہیں۔|جواب مکمل ہونے سے پہلے رک گیا۔|سروس نے یہ درخواست قبول نہیں کی۔|جواب ماڈل کی آؤٹ پٹ حد تک پہنچ گیا۔|درخواست مکمل نہیں ہو سکی۔|جواب جاری رکھنے کے لیے ماڈل سے کہہ سکتے ہیں۔",
        "pa": "Instant ਨਾਲ ਕਿਸੇ ਵੀ ਵੇਲੇ ਤੁਰੰਤ ਜਵਾਬ ਅਤੇ ਦੋ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਅਨੁਵਾਦ ਪ੍ਰਾਪਤ ਕਰੋ।|ਕਿਰਪਾ ਕਰਕੇ {fields} ਭਰੋ।|{settings} (⌘,) ਅਤੇ ਸੈੱਟਅੱਪ ਪੂਰਾ ਹੋਣ ਤੋਂ ਬਾਅਦ Enter ਦਬਾਓ।|ਕਨੈਕਸ਼ਨ ਦੀ ਜਾਣਕਾਰੀ ਭਰੀ ਗਈ ਹੈ। ਹੁਣ ਸਵਾਲ ਪੁੱਛ ਸਕਦੇ ਹੋ।|ਸੈਟਿੰਗਾਂ ਖੋਲ੍ਹੋ|ਪਹਿਲਾਂ ਮਿਲਿਆ ਪਾਠ ਸੰਭਾਲਿਆ ਗਿਆ ਹੈ।|{fields} ਦੀ ਜਾਂਚ ਕਰੋ।|ਨੈੱਟਵਰਕ ਕਨੈਕਸ਼ਨ ਅਤੇ ਪ੍ਰਾਕਸੀ ਦੀ ਜਾਂਚ ਕਰੋ।|ਥੋੜ੍ਹੀ ਦੇਰ ਬਾਅਦ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।|ਪ੍ਰਦਾਤਾ ਦੇ ਖਾਤੇ ਦਾ ਕੋਟਾ ਅਤੇ ਵਰਤੋਂ ਦੀਆਂ ਹੱਦਾਂ ਜਾਂਚੋ।|ਸਵਾਲ ਛੋਟਾ ਕਰੋ ਜਾਂ ਗੱਲਬਾਤ ਸੰਭਾਲ ਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।|ਸਵਾਲ ਨੂੰ ਹੋਰ ਸ਼ਬਦਾਂ ਵਿੱਚ ਲਿਖ ਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।|Base URL ਗਲਤ ਹੈ। https://…/v1 ਵਰਗਾ HTTPS API ਪਤਾ ਵਰਤੋ।|API Key ਦਾ ਫਾਰਮੈਟ ਗਲਤ ਹੈ। ਸਿਰਫ਼ ਪੂਰੀ ਕੁੰਜੀ ਪੇਸਟ ਕਰੋ।|ਪ੍ਰਦਾਤਾ ਦਾ ਮਾਡਲ ID ਖਾਲੀ ਥਾਂ ਤੋਂ ਬਿਨਾਂ ਭਰੋ।|ਕੀਚੇਨ ਤੋਂ API Key ਨਹੀਂ ਪੜ੍ਹੀ ਜਾ ਸਕੀ। ਪਹੁੰਚ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ ਜਾਂ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਮੁੜ ਭਰੋ।|API Key ਕੀਚੇਨ ਵਿੱਚ ਸੰਭਾਲੀ ਨਹੀਂ ਜਾ ਸਕੀ। ਪਹੁੰਚ ਦੀ ਇਜਾਜ਼ਤ ਦੇ ਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।|API Key ਦੀ ਪ੍ਰਮਾਣਿਕਤਾ ਅਸਫਲ ਰਹੀ।|ਮਾਡਲ ਜਾਂ ਸੇਵਾ ਤੱਕ ਪਹੁੰਚ ਰੱਦ ਕੀਤੀ ਗਈ।|ਮਾਡਲ ਨਹੀਂ ਮਿਲਿਆ ਜਾਂ ਇਸ ਪਤੇ 'ਤੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।|API ਪਤਾ ਵਰਤਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ।|ਸੇਵਾ ਦਾ ਕੋਟਾ ਖਤਮ ਜਾਂ ਸੀਮਿਤ ਹੈ।|ਬਹੁਤ ਜ਼ਿਆਦਾ ਬੇਨਤੀਆਂ ਹਨ।|ਮਾਡਲ ਸੇਵਾ ਕੁਝ ਸਮੇਂ ਲਈ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।|ਇਨਪੁੱਟ ਜਾਂ ਗੱਲਬਾਤ ਮਾਡਲ ਦੀ ਹੱਦ ਤੋਂ ਵੱਧ ਹੈ।|ਸੇਵਾ ਨੇ ਬੇਨਤੀ ਰੱਦ ਕੀਤੀ ਜਾਂ ਇਹ API ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ।|ਇੰਟਰਨੈੱਟ ਕਨੈਕਸ਼ਨ ਨਹੀਂ ਹੈ।|ਸੇਵਾ ਨਾਲ ਕਨੈਕਟ ਨਹੀਂ ਹੋ ਸਕਿਆ।|ਬੇਨਤੀ ਦਾ ਸਮਾਂ ਖਤਮ ਹੋ ਗਿਆ।|HTTPS ਸਰਟੀਫਿਕੇਟ ਦੀ ਜਾਂਚ ਅਸਫਲ ਰਹੀ।|ਸੇਵਾ ਨੇ ਦਿਖਾਉਣ ਯੋਗ ਜਵਾਬ ਨਹੀਂ ਦਿੱਤਾ।|ਜਵਾਬ ਦਾ ਸਟ੍ਰੀਮਿੰਗ ਫਾਰਮੈਟ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ।|ਜਵਾਬ ਪੂਰਾ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਰੁਕ ਗਿਆ।|ਸੇਵਾ ਨੇ ਇਹ ਬੇਨਤੀ ਸਵੀਕਾਰ ਨਹੀਂ ਕੀਤੀ।|ਜਵਾਬ ਮਾਡਲ ਦੀ ਆਉਟਪੁੱਟ ਹੱਦ ਤੱਕ ਪਹੁੰਚ ਗਿਆ।|ਬੇਨਤੀ ਪੂਰੀ ਨਹੀਂ ਹੋ ਸਕੀ।|ਜਵਾਬ ਜਾਰੀ ਰੱਖਣ ਲਈ ਮਾਡਲ ਨੂੰ ਕਹਿ ਸਕਦੇ ਹੋ।",
        "id": "Instant selalu siap untuk jawaban cepat dan terjemahan dua bahasa.|Isi {fields}.|{settings} (⌘,), lalu tekan Enter setelah pengaturan selesai.|Informasi koneksi sudah diisi. Anda dapat mulai bertanya.|Buka Pengaturan|Teks yang diterima sebelumnya tetap disimpan.|Periksa {fields}.|Periksa koneksi jaringan dan proksi.|Coba lagi sebentar lagi.|Periksa kuota dan batas penggunaan akun penyedia.|Persingkat pertanyaan atau arsipkan percakapan ini, lalu coba lagi.|Ubah susunan pertanyaan dan coba lagi.|Base URL tidak valid. Gunakan alamat API HTTPS, seperti https://…/v1.|Format API Key tidak valid. Tempel hanya kunci lengkap.|Gunakan ID model dari penyedia tanpa spasi.|API Key tidak dapat dibaca dari Rantai Kunci. Izinkan akses atau isi ulang di Pengaturan.|API Key tidak dapat disimpan ke Rantai Kunci. Izinkan akses lalu coba lagi.|Autentikasi API Key gagal.|Akses ke model atau layanan ditolak.|Model tidak ditemukan atau tidak tersedia pada alamat ini.|Alamat API tidak dapat digunakan.|Kuota layanan habis atau dibatasi.|Terlalu banyak permintaan.|Layanan model sementara tidak tersedia.|Masukan atau percakapan melebihi batas model.|Layanan menolak permintaan atau tidak mendukung API ini.|Tidak ada koneksi internet.|Tidak dapat terhubung ke layanan.|Permintaan kehabisan waktu.|Verifikasi sertifikat HTTPS gagal.|Layanan tidak mengembalikan jawaban yang dapat ditampilkan.|Format streaming respons tidak didukung.|Jawaban terputus sebelum selesai.|Layanan tidak menerima permintaan ini.|Jawaban mencapai batas keluaran model.|Permintaan tidak dapat diselesaikan.|Anda dapat meminta model melanjutkan jawabannya.",
        "ms": "Instant sentiasa tersedia untuk jawapan pantas dan terjemahan dua bahasa.|Isi {fields}.|{settings} (⌘,), kemudian tekan Enter selepas persediaan selesai.|Maklumat sambungan telah diisi. Anda boleh mula bertanya.|Buka Tetapan|Teks yang diterima sebelum ini telah dikekalkan.|Semak {fields}.|Semak sambungan rangkaian dan proksi.|Cuba lagi sebentar lagi.|Semak kuota dan had penggunaan akaun penyedia.|Pendekkan soalan atau arkibkan perbualan ini, kemudian cuba lagi.|Ubah ayat soalan dan cuba lagi.|Base URL tidak sah. Gunakan alamat API HTTPS, seperti https://…/v1.|Format API Key tidak sah. Tampal hanya kunci penuh.|Gunakan ID model penyedia tanpa ruang.|API Key tidak dapat dibaca daripada Rantai Kunci. Benarkan akses atau isi semula dalam Tetapan.|API Key tidak dapat disimpan ke Rantai Kunci. Benarkan akses dan cuba lagi.|Pengesahan API Key gagal.|Akses kepada model atau perkhidmatan ditolak.|Model tidak ditemui atau tidak tersedia di alamat ini.|Alamat API tidak dapat digunakan.|Kuota perkhidmatan habis atau terhad.|Terlalu banyak permintaan.|Perkhidmatan model tidak tersedia buat sementara waktu.|Input atau perbualan melebihi had model.|Perkhidmatan menolak permintaan atau tidak menyokong API ini.|Tiada sambungan internet.|Tidak dapat menyambung kepada perkhidmatan.|Permintaan tamat masa.|Pengesahan sijil HTTPS gagal.|Perkhidmatan tidak memulangkan jawapan yang boleh dipaparkan.|Format penstriman respons tidak disokong.|Jawapan terhenti sebelum selesai.|Perkhidmatan tidak menerima permintaan ini.|Jawapan mencapai had output model.|Permintaan tidak dapat diselesaikan.|Anda boleh meminta model meneruskan jawapannya.",
        "vi": "Instant luôn sẵn sàng trả lời nhanh và dịch song ngữ.|Vui lòng điền {fields}.|{settings} (⌘,), rồi nhấn Enter sau khi thiết lập xong.|Thông tin kết nối đã được điền. Bạn có thể bắt đầu hỏi.|Mở cài đặt|Nội dung đã nhận trước đó được giữ lại.|Kiểm tra {fields}.|Kiểm tra kết nối mạng và proxy.|Vui lòng thử lại sau ít phút.|Kiểm tra hạn mức và giới hạn sử dụng của tài khoản nhà cung cấp.|Rút ngắn câu hỏi hoặc lưu trữ cuộc trò chuyện rồi thử lại.|Diễn đạt lại câu hỏi rồi thử lại.|Base URL không hợp lệ. Dùng địa chỉ API HTTPS, chẳng hạn https://…/v1.|Định dạng API Key không hợp lệ. Chỉ dán toàn bộ khóa.|Dùng ID mô hình của nhà cung cấp, không có khoảng trắng.|Không thể đọc API Key từ Chuỗi khóa. Cho phép truy cập hoặc nhập lại trong Cài đặt.|Không thể lưu API Key vào Chuỗi khóa. Cho phép truy cập rồi thử lại.|Xác thực API Key thất bại.|Quyền truy cập mô hình hoặc dịch vụ bị từ chối.|Không tìm thấy mô hình hoặc mô hình không khả dụng tại địa chỉ này.|Không thể dùng địa chỉ API.|Hạn mức dịch vụ đã hết hoặc bị giới hạn.|Quá nhiều yêu cầu.|Dịch vụ mô hình tạm thời không khả dụng.|Nội dung nhập hoặc cuộc trò chuyện vượt giới hạn mô hình.|Dịch vụ từ chối yêu cầu hoặc không hỗ trợ API này.|Không có kết nối Internet.|Không thể kết nối dịch vụ.|Yêu cầu đã hết thời gian chờ.|Xác minh chứng chỉ HTTPS thất bại.|Dịch vụ không trả về câu trả lời có thể hiển thị.|Định dạng phản hồi truyền trực tiếp không được hỗ trợ.|Câu trả lời bị ngắt trước khi hoàn tất.|Dịch vụ không chấp nhận yêu cầu này.|Câu trả lời đã đạt giới hạn đầu ra của mô hình.|Không thể hoàn tất yêu cầu.|Bạn có thể yêu cầu mô hình trả lời tiếp.",
        "th": "Instant พร้อมตอบคำถามอย่างรวดเร็วและแปลสองภาษาได้ทุกเมื่อ|โปรดกรอก {fields}|{settings} (⌘,) แล้วกด Enter เมื่อกำหนดค่าเสร็จ|กรอกข้อมูลการเชื่อมต่อแล้ว คุณเริ่มถามได้เลย|เปิดการตั้งค่า|เก็บข้อความที่ได้รับก่อนหน้านี้ไว้แล้ว|ตรวจสอบ {fields}|ตรวจสอบการเชื่อมต่อเครือข่ายและพร็อกซี|โปรดลองอีกครั้งในอีกสักครู่|ตรวจสอบโควตาและขีดจำกัดการใช้งานของบัญชีกับผู้ให้บริการ|ย่อคำถามหรือเก็บบทสนทนานี้ถาวรแล้วลองอีกครั้ง|เรียบเรียงคำถามใหม่แล้วลองอีกครั้ง|Base URL ไม่ถูกต้อง ใช้ที่อยู่ HTTPS API เช่น https://…/v1|รูปแบบ API Key ไม่ถูกต้อง วางเฉพาะคีย์ที่ครบถ้วน|ใช้ ID โมเดลของผู้ให้บริการโดยไม่มีช่องว่าง|อ่าน API Key จากพวงกุญแจไม่ได้ โปรดอนุญาตการเข้าถึงหรือกรอกใหม่ในการตั้งค่า|บันทึก API Key ลงพวงกุญแจไม่ได้ โปรดอนุญาตการเข้าถึงแล้วลองอีกครั้ง|การยืนยัน API Key ล้มเหลว|ถูกปฏิเสธการเข้าถึงโมเดลหรือบริการ|ไม่พบโมเดลหรือโมเดลไม่พร้อมใช้ที่ที่อยู่นี้|ใช้ที่อยู่ API ไม่ได้|โควตาบริการหมดหรือถูกจำกัด|มีคำขอมากเกินไป|บริการโมเดลไม่พร้อมใช้งานชั่วคราว|ข้อมูลที่ป้อนหรือบทสนทนาเกินขีดจำกัดของโมเดล|บริการปฏิเสธคำขอหรือไม่รองรับ API นี้|ไม่มีการเชื่อมต่ออินเทอร์เน็ต|เชื่อมต่อบริการไม่ได้|คำขอหมดเวลา|การตรวจสอบใบรับรอง HTTPS ล้มเหลว|บริการไม่ได้ส่งคำตอบที่แสดงได้กลับมา|รูปแบบสตรีมของคำตอบไม่รองรับ|คำตอบถูกขัดจังหวะก่อนเสร็จสมบูรณ์|บริการไม่ยอมรับคำขอนี้|คำตอบถึงขีดจำกัดเอาต์พุตของโมเดล|ดำเนินการตามคำขอไม่สำเร็จ|คุณสามารถขอให้โมเดลตอบต่อได้",
        "fil": "Laging abot-kamay ang Instant para sa mabilis na sagot at pagsasalin sa dalawang wika.|Punan ang {fields}.|{settings} (⌘,), at pindutin ang Enter matapos mag-set up.|Nailagay na ang impormasyon ng koneksyon. Maaari ka nang magtanong.|Buksan ang Mga Setting|Napanatili ang tekstong natanggap na.|Suriin ang {fields}.|Suriin ang koneksyon sa network at proxy.|Subukang muli pagkalipas ng sandali.|Suriin ang quota at mga limitasyon ng account sa provider.|Paikliin ang tanong o i-archive ang pag-uusap at subukang muli.|Isulat sa ibang paraan ang tanong at subukang muli.|Hindi wasto ang Base URL. Gumamit ng HTTPS API address gaya ng https://…/v1.|Hindi wasto ang format ng API Key. Idikit lamang ang buong key.|Gamitin ang model ID ng provider nang walang espasyo.|Hindi mabasa ang API Key mula sa Keychain. Payagan ang access o ilagay muli ito sa Mga Setting.|Hindi ma-save ang API Key sa Keychain. Payagan ang access at subukang muli.|Nabigo ang pagpapatunay ng API Key.|Tinanggihan ang access sa modelo o serbisyo.|Hindi nakita ang modelo o hindi ito magagamit sa address na ito.|Hindi magamit ang API address.|Naubos o nilimitahan ang quota ng serbisyo.|Masyadong maraming kahilingan.|Pansamantalang hindi magagamit ang serbisyo ng modelo.|Lampas sa limitasyon ng modelo ang input o pag-uusap.|Tinanggihan ng serbisyo ang kahilingan o hindi nito sinusuportahan ang API na ito.|Walang koneksyon sa Internet.|Hindi makakonekta sa serbisyo.|Naubos ang oras ng paghihintay sa kahilingan.|Nabigo ang pag-verify sa HTTPS certificate.|Walang ibinalik na sagot na maipapakita ang serbisyo.|Hindi suportado ang streaming format ng sagot.|Naputol ang sagot bago matapos.|Hindi tinanggap ng serbisyo ang kahilingang ito.|Naabot ng sagot ang limitasyon ng output ng modelo.|Hindi makumpleto ang kahilingan.|Maaari mong hilingin sa modelo na ipagpatuloy ang sagot.",
        "sw": "Instant iko karibu kila wakati kwa majibu ya haraka na tafsiri ya lugha mbili.|Jaza {fields}.|{settings} (⌘,), kisha bonyeza Enter baada ya kukamilisha usanidi.|Taarifa za muunganisho zimejazwa. Sasa unaweza kuuliza swali.|Fungua Mipangilio|Maandishi yaliyopokelewa awali yamehifadhiwa.|Kagua {fields}.|Kagua muunganisho wa mtandao na proksi.|Jaribu tena baada ya muda mfupi.|Kagua mgao na vikomo vya matumizi vya akaunti yako kwa mtoa huduma.|Fupisha swali au hifadhi mazungumzo haya kisha ujaribu tena.|Andika swali kwa namna nyingine na ujaribu tena.|Base URL si sahihi. Tumia anwani ya HTTPS API kama https://…/v1.|Muundo wa API Key si sahihi. Bandika ufunguo kamili pekee.|Tumia kitambulisho cha modeli cha mtoa huduma bila nafasi.|API Key haikuweza kusomwa kutoka Keychain. Ruhusu ufikiaji au uiweke tena kwenye Mipangilio.|API Key haikuweza kuhifadhiwa kwenye Keychain. Ruhusu ufikiaji na ujaribu tena.|Uthibitishaji wa API Key umeshindwa.|Ufikiaji wa modeli au huduma umekataliwa.|Modeli haijapatikana au haipatikani kwenye anwani hii.|Anwani ya API haikuweza kutumika.|Mgao wa huduma umeisha au umewekewa kikomo.|Maombi ni mengi sana.|Huduma ya modeli haipatikani kwa muda.|Ingizo au mazungumzo yamezidi kikomo cha modeli.|Huduma imekataa ombi au haiungi mkono API hii.|Hakuna muunganisho wa intaneti.|Imeshindikana kuunganisha kwenye huduma.|Muda wa ombi umeisha.|Uthibitishaji wa cheti cha HTTPS umeshindwa.|Huduma haijarudisha jibu linaloweza kuonyeshwa.|Jibu halina muundo wa utiririshaji unaokubalika.|Jibu limekatika kabla ya kukamilika.|Huduma haijakubali ombi hili.|Jibu limefikia kikomo cha matokeo ya modeli.|Ombi halikuweza kukamilika.|Unaweza kuiomba modeli iendelee na jibu.",
        "es": "Instant está siempre a mano para responder preguntas y traducir a dos idiomas.|Completa {fields}.|{settings} (⌘,) y, tras configurar, pulsa Enter para continuar.|Los datos de conexión están completos. Ya puedes preguntar.|Abrir ajustes|Se ha conservado el texto recibido.|Comprueba {fields}.|Comprueba la conexión de red y el proxy.|Vuelve a intentarlo en unos momentos.|Revisa la cuota y los límites de uso de tu proveedor.|Acorta la pregunta o archiva esta conversación y vuelve a intentarlo.|Reformula la pregunta y vuelve a intentarlo.|Base URL no es válido. Usa una dirección API HTTPS, como https://…/v1.|El formato de API Key no es válido. Pega solo la clave completa.|Usa el ID del modelo del proveedor, sin espacios.|No se pudo leer API Key del Llavero. Permite el acceso o introdúcela en Ajustes.|No se pudo guardar API Key en el Llavero. Permite el acceso y reintenta.|La autenticación de API Key ha fallado.|Se ha denegado el acceso al modelo o servicio.|No se ha encontrado el modelo o no está disponible en esta dirección.|No se pudo utilizar la dirección de la API.|La cuota del servicio se ha agotado o está limitada.|Demasiadas solicitudes.|El servicio del modelo no está disponible temporalmente.|La entrada o conversación supera el límite del modelo.|El servicio ha rechazado la solicitud o no admite esta API.|No hay conexión a Internet.|No se pudo conectar con el servicio.|La solicitud ha agotado el tiempo de espera.|Ha fallado la verificación del certificado HTTPS.|El servicio no ha devuelto una respuesta que se pueda mostrar.|La respuesta no tiene un formato de transmisión compatible.|La respuesta se ha interrumpido antes de terminar.|El servicio no ha aceptado esta solicitud.|La respuesta ha alcanzado el límite de salida del modelo.|No se pudo completar la solicitud.|Puedes pedir al modelo que continúe.",
        "fr": "Instant reste à portée de main pour répondre à vos questions et traduire dans deux langues.|Renseignez {fields}.|{settings} (⌘,), puis appuyez sur Entrée une fois la configuration terminée.|Les informations de connexion sont renseignées. Vous pouvez poser une question.|Ouvrir les réglages|Le texte déjà reçu a été conservé.|Vérifiez {fields}.|Vérifiez la connexion réseau et le proxy.|Réessayez dans quelques instants.|Vérifiez le quota et les limites de votre compte chez le fournisseur.|Raccourcissez la question ou archivez cette conversation, puis réessayez.|Reformulez la question et réessayez.|Base URL est invalide. Utilisez une adresse API HTTPS, comme https://…/v1.|Le format de la clé API est invalide. Collez uniquement la clé complète.|Utilisez l’identifiant du modèle fourni, sans espaces.|Impossible de lire API Key dans le Trousseau. Autorisez l’accès ou saisissez-la dans les réglages.|Impossible d’enregistrer API Key dans le Trousseau. Autorisez l’accès et réessayez.|L’authentification de la clé API a échoué.|L’accès au modèle ou au service a été refusé.|Le modèle est introuvable ou indisponible à cette adresse.|L’adresse de l’API est inutilisable.|Le quota du service est épuisé ou limité.|Trop de requêtes.|Le service du modèle est temporairement indisponible.|La saisie ou la conversation dépasse la limite du modèle.|Le service a rejeté la requête ou ne prend pas en charge cette API.|Aucune connexion Internet.|Impossible de joindre le service.|Le délai de la requête a expiré.|La vérification du certificat HTTPS a échoué.|Le service n’a renvoyé aucune réponse affichable.|La réponse n’utilise pas un format de flux pris en charge.|La réponse a été interrompue avant sa fin.|Le service n’a pas accepté cette requête.|La réponse a atteint la limite de sortie du modèle.|La requête n’a pas pu aboutir.|Vous pouvez demander au modèle de continuer.",
        "de": "Instant ist jederzeit für schnelle Antworten und zweisprachige Übersetzungen erreichbar.|Bitte ergänze {fields}.|{settings} (⌘,) und drücke nach dem Einrichten Enter, um fortzufahren.|Die Verbindungsdaten sind eingetragen. Du kannst jetzt eine Frage stellen.|Einstellungen öffnen|Der bereits empfangene Text wurde behalten.|Prüfe {fields}.|Prüfe Netzwerkverbindung und Proxy.|Versuche es in Kürze erneut.|Prüfe Kontingent und Nutzungslimits bei deinem Anbieter.|Kürze die Frage oder archiviere das Gespräch und versuche es erneut.|Formuliere die Frage um und versuche es erneut.|Base URL ist ungültig. Verwende eine HTTPS-API-Adresse wie https://…/v1.|API Key hat ein ungültiges Format. Füge nur den vollständigen Schlüssel ein.|Verwende die Modell-ID des Anbieters ohne Leerzeichen.|API Key konnte nicht aus dem Schlüsselbund gelesen werden. Erlaube den Zugriff oder gib ihn in den Einstellungen ein.|API Key konnte nicht im Schlüsselbund gespeichert werden. Erlaube den Zugriff und versuche es erneut.|Die Authentifizierung des API-Schlüssels ist fehlgeschlagen.|Der Zugriff auf Modell oder Dienst wurde verweigert.|Das Modell wurde nicht gefunden oder ist an dieser Adresse nicht verfügbar.|Die API-Adresse konnte nicht verwendet werden.|Das Dienstkontingent ist aufgebraucht oder eingeschränkt.|Zu viele Anfragen.|Der Modelldienst ist vorübergehend nicht verfügbar.|Eingabe oder Gespräch überschreiten das Modelllimit.|Der Dienst hat die Anfrage abgelehnt oder unterstützt diese API nicht.|Keine Internetverbindung.|Der Dienst konnte nicht erreicht werden.|Die Anfrage hat das Zeitlimit überschritten.|Die HTTPS-Zertifikatsprüfung ist fehlgeschlagen.|Der Dienst hat keine darstellbare Antwort geliefert.|Die Antwort hat kein unterstütztes Streamingformat.|Die Antwort wurde vorzeitig unterbrochen.|Der Dienst hat diese Anfrage nicht angenommen.|Die Antwort hat das Ausgabelimit des Modells erreicht.|Die Anfrage konnte nicht abgeschlossen werden.|Du kannst das Modell bitten, die Antwort fortzusetzen.",
        "pt": "O Instant está sempre à mão para respostas rápidas e traduções em dois idiomas.|Preencha {fields}.|{settings} (⌘,) e pressione Enter após concluir a configuração.|Os dados de conexão foram preenchidos. Você já pode perguntar.|Abrir ajustes|O texto já recebido foi preservado.|Verifique {fields}.|Verifique a conexão de rede e o proxy.|Tente novamente em instantes.|Verifique a cota e os limites da sua conta no provedor.|Encurte a pergunta ou arquive esta conversa e tente novamente.|Reformule a pergunta e tente novamente.|Base URL é inválido. Use um endereço de API HTTPS, como https://…/v1.|O formato de API Key é inválido. Cole apenas a chave completa.|Use o ID do modelo do provedor, sem espaços.|Não foi possível ler API Key no Acesso às Chaves. Permita o acesso ou insira-a nos Ajustes.|Não foi possível salvar API Key nas Chaves. Permita o acesso e tente novamente.|A autenticação da chave de API falhou.|O acesso ao modelo ou serviço foi negado.|O modelo não foi encontrado ou não está disponível neste endereço.|Não foi possível usar o endereço da API.|A cota do serviço está esgotada ou limitada.|Muitas solicitações.|O serviço do modelo está temporariamente indisponível.|A entrada ou conversa excede o limite do modelo.|O serviço rejeitou a solicitação ou não suporta esta API.|Sem conexão com a Internet.|Não foi possível conectar ao serviço.|O tempo da solicitação se esgotou.|A verificação do certificado HTTPS falhou.|O serviço não retornou uma resposta que possa ser exibida.|A resposta não usa um formato de streaming compatível.|A resposta foi interrompida antes de terminar.|O serviço não aceitou esta solicitação.|A resposta atingiu o limite de saída do modelo.|Não foi possível concluir a solicitação.|Você pode pedir ao modelo para continuar.",
        "it": "Instant è sempre a portata di mano per risposte rapide e traduzioni bilingui.|Compila {fields}.|{settings} (⌘,), poi premi Invio dopo aver completato la configurazione.|I dati di connessione sono compilati. Ora puoi fare una domanda.|Apri impostazioni|Il testo già ricevuto è stato conservato.|Controlla {fields}.|Controlla la connessione di rete e il proxy.|Riprova tra poco.|Controlla la quota e i limiti del tuo account presso il fornitore.|Accorcia la domanda o archivia la conversazione e riprova.|Riformula la domanda e riprova.|Base URL non è valido. Usa un indirizzo API HTTPS, come https://…/v1.|Il formato di API Key non è valido. Incolla solo la chiave completa.|Usa l’ID del modello del fornitore, senza spazi.|Impossibile leggere API Key dal Portachiavi. Consenti l’accesso o inseriscila nelle impostazioni.|Impossibile salvare API Key nel Portachiavi. Consenti l’accesso e riprova.|Autenticazione della chiave API non riuscita.|Accesso al modello o al servizio negato.|Modello non trovato o non disponibile a questo indirizzo.|Impossibile usare l’indirizzo dell’API.|Quota del servizio esaurita o limitata.|Troppe richieste.|Il servizio del modello è temporaneamente indisponibile.|L’input o la conversazione supera il limite del modello.|Il servizio ha rifiutato la richiesta o non supporta questa API.|Connessione Internet assente.|Impossibile connettersi al servizio.|Tempo della richiesta scaduto.|Verifica del certificato HTTPS non riuscita.|Il servizio non ha restituito una risposta visualizzabile.|La risposta non usa un formato di streaming supportato.|La risposta si è interrotta prima del completamento.|Il servizio non ha accettato questa richiesta.|La risposta ha raggiunto il limite di output del modello.|Impossibile completare la richiesta.|Puoi chiedere al modello di continuare.",
        "ru": "Instant всегда под рукой для быстрых ответов и перевода на два языка.|Заполните {fields}.|{settings} (⌘,) и после настройки нажмите Enter, чтобы продолжить.|Данные подключения заполнены. Теперь можно задать вопрос.|Открыть настройки|Ранее полученный текст сохранён.|Проверьте {fields}.|Проверьте подключение к сети и прокси.|Повторите попытку чуть позже.|Проверьте квоту и ограничения аккаунта у поставщика.|Сократите вопрос или архивируйте разговор и повторите попытку.|Переформулируйте вопрос и повторите попытку.|Недопустимый Base URL. Укажите адрес HTTPS API, например https://…/v1.|Неверный формат API Key. Вставьте только полный ключ.|Укажите ID модели поставщика без пробелов.|Не удалось прочитать API Key из Связки ключей. Разрешите доступ или введите ключ в настройках.|Не удалось сохранить API Key в Связке ключей. Разрешите доступ и повторите попытку.|Ошибка проверки API Key.|Доступ к модели или сервису запрещён.|Модель не найдена или недоступна по этому адресу.|Адрес API недоступен.|Квота сервиса исчерпана или ограничена.|Слишком много запросов.|Сервис модели временно недоступен.|Ввод или разговор превышает лимит модели.|Сервис отклонил запрос или не поддерживает этот API.|Нет подключения к Интернету.|Не удалось подключиться к сервису.|Время ожидания запроса истекло.|Ошибка проверки сертификата HTTPS.|Сервис не вернул ответ для отображения.|Формат потокового ответа не поддерживается.|Ответ прервался до завершения.|Сервис не принял этот запрос.|Ответ достиг лимита вывода модели.|Не удалось завершить запрос.|Можно попросить модель продолжить ответ.",
        "uk": "Instant завжди під рукою для швидких відповідей і перекладу двома мовами.|Заповніть {fields}.|{settings} (⌘,) і після налаштування натисніть Enter, щоб продовжити.|Дані підключення заповнено. Тепер можна поставити запитання.|Відкрити параметри|Раніше отриманий текст збережено.|Перевірте {fields}.|Перевірте підключення до мережі та проксі.|Повторіть спробу трохи пізніше.|Перевірте квоту й обмеження облікового запису в постачальника.|Скоротіть запитання або архівуйте розмову й повторіть спробу.|Переформулюйте запитання й повторіть спробу.|Неприпустимий Base URL. Укажіть адресу HTTPS API, як-от https://…/v1.|Неправильний формат API Key. Вставте лише повний ключ.|Укажіть ID моделі постачальника без пробілів.|Не вдалося прочитати API Key із В’язки ключів. Дозвольте доступ або введіть ключ у параметрах.|Не вдалося зберегти API Key у В’язці ключів. Дозвольте доступ і повторіть спробу.|Помилка автентифікації API Key.|Доступ до моделі або сервісу заборонено.|Модель не знайдено або вона недоступна за цією адресою.|Адреса API недоступна.|Квоту сервісу вичерпано або обмежено.|Забагато запитів.|Сервіс моделі тимчасово недоступний.|Введені дані або розмова перевищують ліміт моделі.|Сервіс відхилив запит або не підтримує цей API.|Немає підключення до Інтернету.|Не вдалося підключитися до сервісу.|Час очікування запиту вичерпано.|Помилка перевірки сертифіката HTTPS.|Сервіс не повернув відповіді для відображення.|Формат потокової відповіді не підтримується.|Відповідь перервалася до завершення.|Сервіс не прийняв цей запит.|Відповідь досягла ліміту виведення моделі.|Не вдалося завершити запит.|Можна попросити модель продовжити відповідь.",
        "nl": "Instant is altijd binnen handbereik voor snelle antwoorden en tweetalige vertalingen.|Vul {fields} in.|{settings} (⌘,) en druk na het instellen op Enter om verder te gaan.|De verbindingsgegevens zijn ingevuld. Je kunt nu een vraag stellen.|Open instellingen|Eerder ontvangen tekst is bewaard.|Controleer {fields}.|Controleer je netwerkverbinding en proxy.|Probeer het zo nog eens.|Controleer het tegoed en de gebruikslimieten bij je aanbieder.|Maak de vraag korter of archiveer dit gesprek en probeer opnieuw.|Formuleer de vraag anders en probeer opnieuw.|Base URL is ongeldig. Gebruik een HTTPS-API-adres, zoals https://…/v1.|API Key heeft een ongeldig formaat. Plak alleen de volledige sleutel.|Gebruik de model-ID van de aanbieder, zonder spaties.|API Key kon niet uit de Sleutelhanger worden gelezen. Sta toegang toe of vul de sleutel in bij Instellingen.|API Key kon niet in de Sleutelhanger worden opgeslagen. Sta toegang toe en probeer opnieuw.|Verificatie van API Key mislukt.|Toegang tot dit model of deze dienst is geweigerd.|Het model is niet gevonden of niet beschikbaar op dit adres.|Het API-adres kon niet worden gebruikt.|Het tegoed of quotum is op of beperkt.|Te veel verzoeken.|De modeldienst is tijdelijk niet beschikbaar.|De invoer of het gesprek overschrijdt de modellimiet.|De dienst heeft het verzoek geweigerd of ondersteunt deze API niet.|Geen internetverbinding.|Kan geen verbinding maken met de dienst.|Het verzoek duurde te lang.|Verificatie van het HTTPS-certificaat mislukt.|De dienst heeft geen toonbaar antwoord gegeven.|Het antwoord heeft geen ondersteund streamingformaat.|Het antwoord is voortijdig afgebroken.|De dienst heeft dit verzoek niet geaccepteerd.|Het antwoord heeft de uitvoerlimiet van het model bereikt.|Het verzoek kon niet worden voltooid.|Je kunt het model vragen om verder te gaan.",
        "pl": "Instant jest zawsze pod ręką, by szybko odpowiadać i tłumaczyć na dwa języki.|Uzupełnij {fields}.|{settings} (⌘,), a po konfiguracji naciśnij Enter, aby kontynuować.|Dane połączenia są uzupełnione. Możesz zadać pytanie.|Otwórz ustawienia|Otrzymany wcześniej tekst został zachowany.|Sprawdź {fields}.|Sprawdź połączenie sieciowe i proxy.|Spróbuj ponownie za chwilę.|Sprawdź limit i stan konta u dostawcy.|Skróć pytanie lub zarchiwizuj rozmowę i spróbuj ponownie.|Przeformułuj pytanie i spróbuj ponownie.|Base URL jest nieprawidłowy. Użyj adresu API HTTPS, np. https://…/v1.|Nieprawidłowy format API Key. Wklej tylko pełny klucz.|Wpisz ID modelu dostawcy bez spacji.|Nie można odczytać API Key z Pęku kluczy. Zezwól na dostęp lub wpisz klucz w ustawieniach.|Nie można zapisać API Key w Pęku kluczy. Zezwól na dostęp i spróbuj ponownie.|Uwierzytelnienie API Key nie powiodło się.|Odmówiono dostępu do modelu lub usługi.|Nie znaleziono modelu lub nie jest dostępny pod tym adresem.|Nie można użyć adresu API.|Limit usługi został wyczerpany lub ograniczony.|Zbyt wiele żądań.|Usługa modelu jest chwilowo niedostępna.|Dane lub rozmowa przekraczają limit modelu.|Usługa odrzuciła żądanie lub nie obsługuje tego API.|Brak połączenia z Internetem.|Nie można połączyć się z usługą.|Upłynął limit czasu żądania.|Weryfikacja certyfikatu HTTPS nie powiodła się.|Usługa nie zwróciła odpowiedzi do wyświetlenia.|Odpowiedź ma nieobsługiwany format strumieniowy.|Odpowiedź została przerwana przed zakończeniem.|Usługa nie przyjęła tego żądania.|Odpowiedź osiągnęła limit wyjściowy modelu.|Nie udało się ukończyć żądania.|Możesz poprosić model o kontynuowanie odpowiedzi.",
        "sv": "Instant finns alltid nära till hands för snabba svar och översättning till två språk.|Fyll i {fields}.|{settings} (⌘,) och tryck på Enter när inställningen är klar.|Anslutningsuppgifterna är ifyllda. Nu kan du ställa en fråga.|Öppna inställningar|Tidigare mottagen text har sparats.|Kontrollera {fields}.|Kontrollera nätverksanslutningen och proxyn.|Försök igen om en stund.|Kontrollera kontots kvot och användningsgränser hos leverantören.|Korta frågan eller arkivera samtalet och försök igen.|Formulera om frågan och försök igen.|Base URL är ogiltig. Använd en HTTPS-API-adress, till exempel https://…/v1.|API Key har fel format. Klistra bara in hela nyckeln.|Använd leverantörens modell-ID utan blanksteg.|API Key kunde inte läsas från Nyckelring. Tillåt åtkomst eller ange nyckeln i inställningarna.|API Key kunde inte sparas i Nyckelring. Tillåt åtkomst och försök igen.|Autentisering av API Key misslyckades.|Åtkomst till modellen eller tjänsten nekades.|Modellen hittades inte eller är inte tillgänglig på adressen.|API-adressen kunde inte användas.|Tjänstens kvot är förbrukad eller begränsad.|För många förfrågningar.|Modelltjänsten är tillfälligt otillgänglig.|Indata eller samtalet överskrider modellens gräns.|Tjänsten avvisade förfrågan eller stöder inte detta API.|Ingen internetanslutning.|Det gick inte att ansluta till tjänsten.|Förfrågan tog för lång tid.|Verifiering av HTTPS-certifikatet misslyckades.|Tjänsten gav inget svar som kan visas.|Svaret har inget strömningsformat som stöds.|Svaret avbröts innan det var klart.|Tjänsten accepterade inte förfrågan.|Svaret nådde modellens utdatagräns.|Förfrågan kunde inte slutföras.|Du kan be modellen att fortsätta svaret.",
        "el": "Το Instant είναι πάντα διαθέσιμο για γρήγορες απαντήσεις και μετάφραση σε δύο γλώσσες.|Συμπληρώστε {fields}.|{settings} (⌘,) και πατήστε Enter μόλις ολοκληρώσετε τη ρύθμιση.|Τα στοιχεία σύνδεσης συμπληρώθηκαν. Μπορείτε να κάνετε μια ερώτηση.|Άνοιγμα ρυθμίσεων|Το κείμενο που είχε ληφθεί διατηρήθηκε.|Ελέγξτε {fields}.|Ελέγξτε τη σύνδεση δικτύου και τον διακομιστή μεσολάβησης.|Δοκιμάστε ξανά σε λίγο.|Ελέγξτε το υπόλοιπο και τα όρια χρήσης στον πάροχο.|Συντομεύστε την ερώτηση ή αρχειοθετήστε τη συνομιλία και δοκιμάστε ξανά.|Αναδιατυπώστε την ερώτηση και δοκιμάστε ξανά.|Το Base URL δεν είναι έγκυρο. Χρησιμοποιήστε διεύθυνση API HTTPS, όπως https://…/v1.|Η μορφή του API Key δεν είναι έγκυρη. Επικολλήστε μόνο ολόκληρο το κλειδί.|Χρησιμοποιήστε το αναγνωριστικό μοντέλου του παρόχου χωρίς κενά.|Δεν ήταν δυνατή η ανάγνωση του API Key από την Κλειδοθήκη. Επιτρέψτε την πρόσβαση ή εισαγάγετέ το στις ρυθμίσεις.|Δεν ήταν δυνατή η αποθήκευση του API Key στην Κλειδοθήκη. Επιτρέψτε την πρόσβαση και δοκιμάστε ξανά.|Η επαλήθευση του API Key απέτυχε.|Η πρόσβαση στο μοντέλο ή στην υπηρεσία απορρίφθηκε.|Το μοντέλο δεν βρέθηκε ή δεν διατίθεται σε αυτή τη διεύθυνση.|Η διεύθυνση API δεν μπορεί να χρησιμοποιηθεί.|Το όριο της υπηρεσίας εξαντλήθηκε ή περιορίστηκε.|Υπερβολικά πολλά αιτήματα.|Η υπηρεσία μοντέλου δεν είναι προσωρινά διαθέσιμη.|Η είσοδος ή η συνομιλία υπερβαίνει το όριο του μοντέλου.|Η υπηρεσία απέρριψε το αίτημα ή δεν υποστηρίζει αυτό το API.|Δεν υπάρχει σύνδεση στο Διαδίκτυο.|Δεν ήταν δυνατή η σύνδεση στην υπηρεσία.|Το αίτημα έληξε λόγω χρονικού ορίου.|Η επαλήθευση του πιστοποιητικού HTTPS απέτυχε.|Η υπηρεσία δεν επέστρεψε απάντηση που να μπορεί να εμφανιστεί.|Η απόκριση δεν έχει υποστηριζόμενη μορφή ροής.|Η απάντηση διακόπηκε πριν ολοκληρωθεί.|Η υπηρεσία δεν δέχτηκε αυτό το αίτημα.|Η απάντηση έφτασε το όριο εξόδου του μοντέλου.|Το αίτημα δεν μπόρεσε να ολοκληρωθεί.|Μπορείτε να ζητήσετε από το μοντέλο να συνεχίσει.",
        "tr": "Instant, hızlı yanıtlar ve iki dilli çeviri için her zaman elinizin altında.|{fields} alanlarını doldurun.|{settings} (⌘,) ve yapılandırma bitince devam etmek için Enter'a basın.|Bağlantı bilgileri dolduruldu. Artık soru sorabilirsiniz.|Ayarları aç|Önceden alınan metin korundu.|{fields} alanlarını kontrol edin.|Ağ bağlantısını ve proxy ayarlarını kontrol edin.|Biraz sonra yeniden deneyin.|Sağlayıcı hesabınızın kotasını ve kullanım sınırlarını kontrol edin.|Soruyu kısaltın veya konuşmayı arşivleyip yeniden deneyin.|Soruyu yeniden ifade edip deneyin.|Base URL geçersiz. https://…/v1 gibi bir HTTPS API adresi kullanın.|API Key biçimi geçersiz. Yalnızca anahtarın tamamını yapıştırın.|Sağlayıcının model kimliğini boşluksuz kullanın.|API Key, Anahtar Zinciri'nden okunamadı. Erişime izin verin veya Ayarlar'da yeniden girin.|API Key, Anahtar Zinciri'ne kaydedilemedi. Erişime izin verip yeniden deneyin.|API Key doğrulaması başarısız.|Modele veya hizmete erişim reddedildi.|Model bulunamadı veya bu adreste kullanılamıyor.|API adresi kullanılamadı.|Hizmet kotası tükendi veya kısıtlandı.|Çok fazla istek.|Model hizmeti geçici olarak kullanılamıyor.|Girdi veya konuşma model sınırını aşıyor.|Hizmet isteği reddetti veya bu API'yi desteklemiyor.|İnternet bağlantısı yok.|Hizmete bağlanılamadı.|İstek zaman aşımına uğradı.|HTTPS sertifika doğrulaması başarısız.|Hizmet görüntülenebilir bir yanıt döndürmedi.|Yanıt desteklenen bir akış biçiminde değil.|Yanıt tamamlanmadan kesildi.|Hizmet bu isteği kabul etmedi.|Yanıt modelin çıktı sınırına ulaştı.|İstek tamamlanamadı.|Modelden yanıta devam etmesini isteyebilirsiniz.",
        "en": "Instant is always within reach for quick answers and bilingual translation.|Please fill in {fields}.|{settings} (⌘,), then press Enter to continue once configured.|Connection details are filled in. You can ask a question now.|Open Settings|Previously received text has been kept.|Check {fields}.|Check your network connection and proxy.|Try again shortly.|Check your provider account's quota and usage limits.|Shorten the question or archive this conversation and try again.|Rephrase the question and try again.|Base URL is invalid. Use an HTTPS API address, such as https://…/v1.|API Key has an invalid format. Paste only the complete key.|Use the provider's model ID, without whitespace.|Instant could not read your API Key from Keychain. Allow access or enter it in Settings.|API Key could not be saved to Keychain. Allow access and try again.|API Key authentication failed.|Access to this model or service was denied.|The model was not found or is unavailable at this endpoint.|The API endpoint could not be used.|The service's quota was exhausted or restricted.|Too many requests.|The model service is temporarily unavailable.|The input or conversation exceeds the model's limit.|The service rejected the request or does not support this API.|No internet connection.|Instant could not connect to the service.|The request timed out.|HTTPS certificate verification failed.|The service returned no displayable answer.|The response is not a supported streaming format.|The answer ended before completion.|The service declined this request.|The answer reached the model's output limit.|The request could not be completed.|Ask a follow-up to continue the answer.",
        "zh-Hans": "Instant 让你随时提问，也支持双语翻译。|请填写 {fields}。|{settings}（⌘,），完成后按 Enter 继续。|设置已填写，可以开始提问了。|打开设置|已保留此前收到的内容。|请检查 {fields}。|请检查网络连接和代理设置。|请稍后再试。|请在服务方控制台检查账户额度及调用限制。|请缩短问题，或归档当前对话后再试。|请调整问题后再试。|Base URL 格式无效，请填写 HTTPS API 地址，例如 https://…/v1。|API Key 格式不正确，请只粘贴完整密钥。|请填写服务提供的模型 ID，不要包含空白字符。|无法从钥匙串读取 API Key。请允许访问，或在设置中重新填写。|API Key 未能保存到钥匙串。请允许访问后再试。|API Key 未通过验证。|服务拒绝访问当前模型或接口。|找不到该模型，或当前接口不支持此模型。|API 接口地址不可用。|服务额度不足或受到限制。|请求过于频繁。|模型服务暂时不可用。|输入或对话长度超过模型限制。|服务拒绝了请求，或不支持此 API。|当前没有网络连接。|无法连接模型服务。|请求超时。|HTTPS 证书验证失败。|服务未返回可显示的回答。|服务返回的内容不符合支持的流式格式。|回答在完成前中断。|服务未接受这项请求。|回答达到模型的输出长度上限。|请求未能完成。|可以继续追问，让模型接着回答。",
        "zh-Hant": "Instant 讓你隨時提問，也支援雙語翻譯。|請填寫 {fields}。|{settings}（⌘,），完成後按 Enter 繼續。|設定已填寫，可以開始提問了。|開啟設定|已保留先前收到的內容。|請檢查 {fields}。|請檢查網路連線和代理設定。|請稍後再試。|請在服務供應商控制台檢查帳戶額度及呼叫限制。|請縮短問題，或封存目前對話後再試。|請調整問題後再試。|Base URL 格式無效，請填寫 HTTPS API 位址，例如 https://…/v1。|API Key 格式不正確，請只貼上完整金鑰。|請填寫服務提供的模型 ID，不要包含空白字元。|無法從鑰匙圈讀取 API Key。請允許存取，或在設定中重新填寫。|API Key 未能儲存到鑰匙圈。請允許存取後再試。|API Key 未通過驗證。|服務拒絕存取目前模型或介面。|找不到此模型，或目前介面不支援此模型。|API 介面位址無法使用。|服務額度不足或受到限制。|請求過於頻繁。|模型服務暫時無法使用。|輸入或對話長度超過模型限制。|服務拒絕了請求，或不支援此 API。|目前沒有網路連線。|無法連線到模型服務。|請求逾時。|HTTPS 憑證驗證失敗。|服務未傳回可顯示的回答。|服務傳回的內容不符合支援的串流格式。|回答在完成前中斷。|服務未接受此請求。|回答達到模型的輸出長度上限。|請求未能完成。|可以繼續追問，讓模型接著回答。",
        "ja": "Instant は、すばやい質問と回答、二言語への翻訳をいつでも使えるアプリです。|{fields} を入力してください。|{settings}（⌘,）で設定し、Enter で続けてください。|設定が入力されました。質問を始められます。|設定を開く|受信済みの内容は保持されています。|{fields} を確認してください。|ネットワークとプロキシの設定を確認してください。|しばらくしてから再試行してください。|提供元の管理画面で利用枠と制限を確認してください。|質問を短くするか、会話をアーカイブして再試行してください。|質問を言い換えて再試行してください。|Base URL が無効です。https://…/v1 のような HTTPS API アドレスを入力してください。|API Key の形式が無効です。キー本体だけを完全に貼り付けてください。|提供元のモデル ID を空白なしで入力してください。|キーチェーンから API Key を読み取れません。アクセスを許可するか、設定で入力し直してください。|API Key をキーチェーンに保存できません。アクセスを許可して再試行してください。|API Key の認証に失敗しました。|このモデルまたは API へのアクセスが拒否されました。|モデルが見つからないか、この接続先では利用できません。|API の接続先を利用できません。|サービスの利用枠が不足しているか制限されています。|リクエストが多すぎます。|モデルサービスを一時的に利用できません。|入力または会話がモデルの長さ制限を超えています。|リクエストが拒否されたか、この API は未対応です。|インターネットに接続されていません。|モデルサービスに接続できません。|リクエストがタイムアウトしました。|HTTPS 証明書の検証に失敗しました。|表示できる回答が返されませんでした。|対応するストリーミング形式で応答されませんでした。|回答が完了前に中断しました。|サービスがこのリクエストを受け付けませんでした。|回答がモデルの出力上限に達しました。|リクエストを完了できませんでした。|続きが必要な場合は、続けるように質問してください。",
        "ko": "Instant로 언제든 빠르게 질문하고 답을 받거나 두 언어로 번역할 수 있습니다.|{fields}을(를) 입력해 주세요.|{settings}(⌘,)에서 설정한 뒤 Enter로 계속하세요.|설정이 입력되었습니다. 이제 질문할 수 있습니다.|설정 열기|이전에 받은 내용은 보존되었습니다.|{fields}을(를) 확인해 주세요.|네트워크 연결과 프록시 설정을 확인해 주세요.|잠시 후 다시 시도해 주세요.|제공업체 콘솔에서 계정 할당량과 사용 한도를 확인해 주세요.|질문을 줄이거나 대화를 보관한 후 다시 시도해 주세요.|질문을 바꾸어 다시 시도해 주세요.|Base URL이 잘못되었습니다. https://…/v1 같은 HTTPS API 주소를 입력해 주세요.|API Key 형식이 잘못되었습니다. 키 자체만 빠짐없이 붙여넣어 주세요.|공백 없이 제공업체의 모델 ID를 입력해 주세요.|키체인에서 API Key를 읽을 수 없습니다. 접근을 허용하거나 설정에서 다시 입력해 주세요.|API Key를 키체인에 저장하지 못했습니다. 접근을 허용하고 다시 시도해 주세요.|API Key 인증에 실패했습니다.|모델 또는 API 접근이 거부되었습니다.|모델을 찾을 수 없거나 이 주소에서 지원하지 않습니다.|API 주소를 사용할 수 없습니다.|서비스 할당량이 부족하거나 제한되었습니다.|요청이 너무 많습니다.|모델 서비스를 일시적으로 사용할 수 없습니다.|입력 또는 대화가 모델의 길이 제한을 초과했습니다.|서비스가 요청을 거부했거나 이 API를 지원하지 않습니다.|인터넷에 연결되어 있지 않습니다.|모델 서비스에 연결할 수 없습니다.|요청 시간이 초과되었습니다.|HTTPS 인증서 검증에 실패했습니다.|표시할 수 있는 답변이 반환되지 않았습니다.|응답이 지원되는 스트리밍 형식이 아닙니다.|답변이 완료되기 전에 중단되었습니다.|서비스가 이 요청을 수락하지 않았습니다.|답변이 모델의 출력 한도에 도달했습니다.|요청을 완료할 수 없습니다.|이어서 답하도록 추가로 질문할 수 있습니다."
    ]
}

extension L10n {
    var connectionCopy: ConnectionCopy { ConnectionCopy(language: language) }
    private var connectionSettingsLink: String { "[\(connectionCopy[.openSettings])](instant://settings)" }
    private func connectionFields(_ fields: [ConnectionField]) -> String {
        let labels = fields.map { field in
            switch field {
            case .baseURL: return "Base URL"
            case .apiKey: return "API Key"
            case .model: return self["model"]
            }
        }
        let formatter = ListFormatter()
        formatter.locale = Locale(identifier: language.id)
        return formatter.string(from: labels) ?? labels.joined(separator: ", ")
    }
    func connectionGuidance(_ issue: ConnectionIssue) -> String {
        let copy = connectionCopy
        let action = copy[.configure].replacingOccurrences(of: "{settings}", with: connectionSettingsLink)
        switch issue {
        case .missing(let fields):
            let intro = fields.count == ConnectionField.allCases.count ? copy[.intro] + "\n\n" : ""
            return intro + copy[.missing].replacingOccurrences(of: "{fields}", with: connectionFields(fields)) + "\n" + action
        case .invalidURL: return copy[.invalidURL] + "\n" + action
        case .invalidKey: return copy[.invalidKey] + "\n" + action
        case .invalidModel: return copy[.invalidModel] + "\n" + action
        case .keychainUnavailable: return copy[.keychain] + "\n" + action
        }
    }
    func modelFailureGuidance(_ error: Error, hasPartialAnswer: Bool) -> String {
        if case ChatError.configuration(let issue) = error { return connectionGuidance(issue) }
        if case ChatError.invalidURL = error { return connectionGuidance(.invalidURL) }
        if case ChatError.missingKey = error { return connectionGuidance(.missing([.apiKey])) }
        let reason = ModelFailureReason.classify(error)
        let copy = connectionCopy
        var lines = [copy[ConnectionCopyKey(rawValue: reason.rawValue) ?? .unknown]]
        if hasPartialAnswer { lines.append(copy[.preserved]) }
        let fields: [ConnectionField]
        switch reason {
        case .authentication: fields = [.baseURL, .apiKey]
        case .permission: fields = [.apiKey, .model]
        case .model, .endpoint, .rejected, .format, .empty: fields = [.baseURL, .model]
        case .network, .certificate: fields = [.baseURL]
        case .unknown: fields = ConnectionField.allCases
        default: fields = []
        }
        if !fields.isEmpty { lines.append(copy[.checkFields].replacingOccurrences(of: "{fields}", with: connectionFields(fields))) }
        switch reason {
        case .offline, .network, .certificate: lines.append(copy[.checkNetwork])
        case .rateLimited, .unavailable, .timeout: lines.append(copy[.later])
        case .quota: lines.append(copy[.checkAccount])
        case .contextLimit: lines.append(copy[.shorten])
        case .outputLimit: lines.append(copy[.continueAnswer])
        case .filtered: lines.append(copy[.rephrase])
        default: break
        }
        if !fields.isEmpty { lines.append("\(connectionSettingsLink) · ⌘, · \(self["retry"])") }
        else if ![.filtered, .outputLimit, .contextLimit].contains(reason) { lines.append(self["retry"]) }
        return lines.joined(separator: "\n")
    }
}
